### PR TITLE
jdk9+ compilation

### PR DESCRIPTION
**Pull request by diuis**
Enabled java 9+ compilation (with the introduction of activation api at runtime scope).
Removed already defined maven plugin versions (some was outdated).
Updated cxf-integration-cdi to the latest minor release.
Updated gitignore for Eclipse IDE users.

### CODE REVIEW

**Comment by deki** [comment]
As we now have CXF 3.3.0 in master, I tried to compile using JDK 11. Anyone seen this before? 

> [INFO] Compiling 58 source files to /home/jenkins/jenkins-slave/workspace/Geronimo-OpenAPI/geronimo-openapi-impl/target/classes
> 
> compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.1, {1}, {2}, {3}, {4}, {5}, {6}, {7}
> java.lang.AssertionError
> 	at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
> 	at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
> 	at jdk.compiler/com.sun.tools.javac.comp.DeferredAttr$2$1.setOverloadKind(DeferredAttr.java:172)

Full log can be found here: https://builds.apache.org/view/E-G/view/Geronimo%20Components%20and%20Specs/job/Geronimo-OpenAPI/4/console

Is it a compiler bug?

**Comment by rmannibucau** [comment]
@deki yes but we'll work it around

**Comment by deki** [comment]
Thanks, I can confirm that compilation now works on master. @diuis please close this PR after you verified this.

**Comment by diuis** [comment]
geronimo openapi compilation works with (Oracle) jdk 11.0.2

**Pull request closed without merging**
