### PR TITLE
add integration-test for maven-plugin, update some versions

### PR DESCRIPTION
**Pull request by deki**

### CODE REVIEW

**Comment by deki** [comment]
@rmannibucau I've just resolved conflicts, would be great if you could merge it.

**Comment by deki** [comment]
@rmannibucau of course, you are right. I've added a script for that.

**Comment by rmannibucau** [comment]
@deki I'm fine like that but thought I would ask you if you want to unmarshall the json to check some of its shape in the bsh script, cause current check validates it was generated but not it is usable. Wdyt?

**Comment by deki** [comment]
@rmannibucau yeah that's easy by using a validator.

```
com.reprezen.kaizen.oasparser.OpenApi3Parser parser = new com.reprezen.kaizen.oasparser.OpenApi3Parser();
return parser.parse(generated, true).isValid();
```
Currently the generated specs are invalid therefore the build fails. I started fixing that and will add this to the verify script as soon as the specs are valid.

**Comment by rmannibucau** [comment]
Was more thinking reusing our own code, potentially with a validate new service if you feel it can be reusable ;) - it can clearly be in a mojo IMHO. I would try to avoid to add deps for this kind of test cause then we have to maintain it and keep scanning them + they pollute the execution stack easily (not for invoker usage i agree but since it is used there it can end up in tests which can be an issue). Hope it makes sense

Side note: no issue merging without then enhance in another pr, just let me know

**Comment by deki** [comment]
Well good ideas for the future, I suggest to merge this one and enhance it later as I'd like to focus on improving other areas first.

**Comment by rmannibucau** [comment]
Oki, created GERONIMO-6684 and GERONIMO-6685 for this PR and applied it.

**Pull request merged**
