### PR TITLE
[GERONIMO-6683] fixed missing mapping for Parameter.In

### PR DESCRIPTION
**Pull request by deki**

### CODE REVIEW

**Comment by rmannibucau** [comment]
@deki small unit test please :angel:  ? (no need to use CDI if you don't want, a plain se test of the processor is more than enough)

**Comment by deki** [comment]
I'll create a test.

**Comment by deki** [comment]
I cannot run unittests from IDE:

```
java.lang.ClassCastException: Cannot cast sun.misc.Launcher$AppClassLoader to org.apache.catalina.loader.ParallelWebappClassLoader

	at java.lang.Class.cast(Class.java:3369)
	at org.apache.geronimo.microprofile.openapi.test.TckMetaInfBugWorkaround.create(TckMetaInfBugWorkaround.java:40)
	at org.apache.geronimo.microprofile.openapi.test.TckMetaInfBugWorkaround.getConfigSources(TckMetaInfBugWorkaround.java:35)
	at org.apache.geronimo.config.DefaultConfigBuilder.lambda$build$0(DefaultConfigBuilder.java:135)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.apache.geronimo.config.DefaultConfigBuilder.build(DefaultConfigBuilder.java:134)
	at org.apache.geronimo.config.DefaultConfigProvider.getConfig(DefaultConfigProvider.java:62)
	at org.apache.geronimo.config.DefaultConfigProvider.getConfig(DefaultConfigProvider.java:46)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:89)
	at org.apache.geronimo.microprofile.openapi.config.OpenAPIConfigMpConfigImpl.<init>(OpenAPIConfigMpConfigImpl.java:29)
	at org.apache.geronimo.microprofile.openapi.config.GeronimoOpenAPIConfig.create(GeronimoOpenAPIConfig.java:26)
	at org.apache.geronimo.microprofile.openapi.impl.processor.AnnotationProcessorTest.ensureParametersAreMapped(AnnotationProcessorTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

```

Will try to fix that as well...

**Comment by deki** [comment]
I've added a testcase. Will extend that with other PRs along with the fixes for missing stuff.

Regarding `TckMetaInfBugWorkaround` is it ok add an instance of check and skip if the classloader is not `ParallelWebappClassLoader`?

**Comment by rmannibucau** [comment]
@deki while tck run yes (as the name implies it shouldnt even exist ;)). You can also not use arquillian at all which is good for this kind of fix too

**Comment by deki** [comment]
Ok added a check as seperate PR

**Pull request merged**
